application: glasstest23
version: 5
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /.*
  script: main.app
  secure: always

- url: /
  static_dir: static_files
  secure: always


libraries:
- name: jinja2
  version: latest


skip_files:
# Default patterns skipped by App Engine, which must be repeated since
# specifying skip_files overrides them otherwise.  See
# https://developers.google.com/appengine/docs/python/config/appconfig#Skipping_Files.
- ^(.*/)?app\.yaml
- ^(.*/)?app\.yml
- ^(.*/)?index\.yaml
- ^(.*/)?index\.yml
- ^(.*/)?#.*#
- ^(.*/)?.*~
- ^(.*/)?.*\.py[co]
- ^(.*/)?.*/RCS/.*
- ^(.*/)?\..*
- ^.*\.pyc$